### ISSUE TITLE
How to populate a form from a datum?

### ISSUE THREAD

**Issue by ghost** [Happstack/reform#5]
Reform nicely handles these use cases:
* Display an empty form: `viewForm`
* Handle submitted data to produce a partially filled out form or a completed datum: `eitherForm`

However I haven't figured out how to achieve this use case:
* Display a filled out form for the user to modify an existing datum: ??

Is there such a feature in Reform?

**Comment by ghost** [comment]
[Based on this thread in `digestive-functors`](https://github.com/jaspervdj/digestive-functors/issues/97), this functionality seems to be covered by `NoEnvironment` constructor for [`Environment`](https://hackage.haskell.org/package/reform-0.2.7.1/docs/Text-Reform-Core.html#t:Environment), which allows you to use injected info from the form definition.

**Comment by stepcut** [comment]
This could be more clearly documented. 

If you look at a function like `inputText` it allows you to provide the initial value,

http://hackage.haskell.org/package/reform-hsp-0.2.7.1/docs/Text-Reform-HSP-Text.html

So if you look at a function like this `pageFormlet` you'll see it takes a `Page` and returns the modified `Page`,

https://github.com/clckwrks/clckwrks-plugin-page/blob/master/Clckwrks/Page/Admin/EditPage.hs#L52

If you peer through the ugliness you'll see that the initial form values are extracted from the `page` value,

     textarea 80 25 (markup (pageSrc page))

This is clearly something that should be shown more explicitly in this tutorial, 

http://happstack.com/docs/crashcourse/Reform.html#reform
